version: 2.1

parameters:
  nombre:
    type: string
    default: "Jairo"

jobs:
  saludo:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          command: echo "Hola, este es un saludo desde CircleCI por parte de << pipeline.parameters.nombre >>"

  despidete:
    docker:
      - image: cimg/base:stable
    steps:
      - run : echo "chao 1"
      - run : echo "chao 2"
      - run : echo "chao 3"


workflows:
  workflows1:
    jobs:
      - saludo
      - despidete
  workflows2:
    jobs:
      - saludo
      - despidete:
          requires:
            - saludo
  workflows3:
    jobs:
      - saludo
      - approval:
          type: approval
          requires:
            - saludo
      - despidete:
          requires:
            - approval

  workflows4:
    jobs:
      - saludo
      - despidete
  
