version: 2.1

jobs:
  saludo:
    docker:
      - image: cimg/base:stable
    steps:
      - run : echo "Hola, este es un saludo desde CircleCI"

  despidete:
    docker:
      - image: cimg/base:stable
    steps:
      - run : echo "chao 1"
      - run : echo "chao 2"
      - run : echo "chao 3"


workflows:
  workflows1:
    jobs:
      - saludo
      - despidete
  workflows2:
    jobs:
      - saludo
      - despidete:
          requires:
            - saludo
  workflows3:
    jobs:
      - saludo
      - approval:
          type: approval
          requires:
            - saludo
      - despidete:
          requires:
            - approval

  workflows4:
    triggers:
      - schedule:
           # 02:22 UTC = 9:22 p. m. en Colombia (America/Bogota, UTC-5)
           cron: "22 2 * * *"
           filters:
             branches:
               only: main

    jobs:
      - saludo
      - despidete
